### ISSUE TITLE
Modelar banco de dados

### ISSUE THREAD

**Issue by Mateuslpds** [Mateuslpds/desapeguei#10]
**Eu** como desenvolvedor
**Quero** modelar o banco de dados
**Para** definir as entidades, relacionamentos e atributos.

- [x] Criar modelo conceitual
- [x] Criar modelo lógico
- [x] Criar modelo físico

**Comment by ianq1w1** [comment]
![image](https://user-images.githubusercontent.com/105610821/197085584-6c2ac82d-921e-416e-ab89-8362e9b132c7.png)
toma

**Comment by ianq1w1** [comment]
![image](https://user-images.githubusercontent.com/105610821/197087509-f8f4169c-8c12-4dcb-a1e4-94b71a0750b1.png)
olha ai

**Comment by ianq1w1** [comment]
![image](https://user-images.githubusercontent.com/105610821/197091323-48168fcd-4f9f-4df9-a124-c4c689e4c990.png)
olha o outro

**Comment by ianq1w1** [comment]
![imagem_2022-11-03_210013601](https://user-images.githubusercontent.com/105610821/199857151-124a44f2-9cbb-431a-87c3-f423337ff039.png)

modelo conceitual

**Comment by ianq1w1** [comment]
![CONCEITUAL2_DESAPEGUEI](https://user-images.githubusercontent.com/105610821/200147234-bcfbec6f-4648-41d2-8e9a-9cc51838fff1.png

conceitual agora vai

**Comment by ianq1w1** [comment]
![CONCEITUAL2_DESAPEGUEI](https://user-images.githubusercontent.com/105610821/200147247-75ae809f-4915-4f5a-8e12-e0964c62b469.png)

conceitual agora vai

**Comment by ianq1w1** [comment]
![imagem_2022-11-05_204508999](https://user-images.githubusercontent.com/105610821/200147257-02db2f57-bb52-46ce-8c14-f168340c840f.png)

logico, esse tem que ir

**Comment by ianq1w1** [comment]
![imagem_2022-11-08_020340201](https://user-images.githubusercontent.com/105610821/200479475-6d967841-12f7-45fe-9ed2-7151c6361934.png)

esse tem q ir

**Comment by ianq1w1** [comment]
![LOGICO100%ATUALIZADORUIMDEATURAR](https://user-images.githubusercontent.com/105610821/200644300-95da3c48-8459-448e-840c-30b458876ad5.png)


100% ATUALIZADO É RUIM DE ATURAR

**Comment by ianq1w1** [comment]
[DESAPEGUEILOG.zip](https://github.com/Mateuslpds/desapeguei/files/10145457/DESAPEGUEILOG.zip)
arquivo do modelo lógico zipado
