### ISSUE TITLE
Doação de objetos 

### ISSUE THREAD

**Issue by ianq1w1** [Mateuslpds/desapeguei#11]
**Eu** como usuário doador 
 **Quero** doar meu objeto
 **Para** realizar o descarte de meu eletrônico 

- [x] Protótipo da tela de doação 
- [x] Tela de doação (front)
- [x] Enviar os dados do objeto para o banco de dados
- [x] Associar a entidade do objeto ao usuário e ao tipo

**Comment by CarolayneMR** [comment]
Ideia do front/design da caixinha vr. sem doações.
![image](https://user-images.githubusercontent.com/108769461/209589189-0ba8d6d2-8b1c-4da0-9244-8e5db513c3ab.png)

**Comment by CarolayneMR** [comment]
Ideia do front/design da caixinha vr. usuário fez doação. (_Sujeito a alterações_)
![image](https://user-images.githubusercontent.com/108769461/209589244-bda8c21f-b2f3-4311-b12a-e604ca659a9a.png)
