### ISSUE TITLE
Home do Desapeguei

### ISSUE THREAD

**Issue by ianq1w1** [Mateuslpds/desapeguei#12]
**Eu** como usuário  
**Quero** ver os objetos disponíveis na HOME
**Para** minha visualização das doações disponíveis

- [x] Protótipo da home 
- [x] Modelo da home no front-end 
- [x] Relacionar as doações feitas com o aparecimento das mesmas na Home

**Comment by CarolayneMR** [comment]
Primeira tentativa! Bora ver no como fica no final :D
![image](https://user-images.githubusercontent.com/108769461/203179391-1f002b3e-400f-49e0-99a1-3c4cdd95cdc0.png)

**Comment by Dudu200313** [comment]
![WhatsApp Image 2022-12-19 at 19 46 39](https://user-images.githubusercontent.com/113178385/208541811-ea7fda78-b5d8-4bad-95f1-bf6e3b250b27.jpeg)

**Comment by CarolayneMR** [comment]
Primeira ideia do design da Home. [ Feito originalmente em 21.11.2022 ]
![image](https://user-images.githubusercontent.com/108769461/208542533-40517976-e496-40a5-9c29-b9224f9beb4d.png)

**Comment by CarolayneMR** [comment]
**Pequeno** update na ideia do design do front-end.
![image](https://user-images.githubusercontent.com/108769461/208541490-7b3908ae-309d-4aa9-956e-bb9a01204df5.png)
