### ISSUE TITLE
Cadastrar usuários

### ISSUE THREAD

**Issue by Mateuslpds** [Mateuslpds/desapeguei#7]
**Eu** como usuário
**Quero** me cadastrar no sistema
**Para** ter acesso as funcionalidades do sistema.

- [x] Criar protótipo da tela
- [x] Criar front-end
- [x] Definir Limite dos campos
- [x] Definir Campos obrigatórios
- [x] Criar opção de tornar a senha visível

**Comment by CarolayneMR** [comment]
Ideia _oficial_ do protótipo da tela de cadastro criada, cores sujeitas a serem alteradas.

![image](https://user-images.githubusercontent.com/108769461/196311707-cfae05b6-9a8d-4356-9b29-6310d19152e1.png)

**Comment by ianq1w1** [comment]
parabains
