### ISSUE TITLE
Autenticar usuários

### ISSUE THREAD

**Issue by Mateuslpds** [Mateuslpds/desapeguei#8]
**Eu** como usuário cadastrado
**Quero** me autenticar no site
**Para** ver as informações e possivelmente fazer ou receber uma doação.

- [x] Criar protótipo da tela
- [x] Criar front-end
- [x] Criar uma verificação de dados incorretos
- [x] Criar alerta de campos não preenchidos
- [x] Criar opção de tornar a senha visível

**Comment by CarolayneMR** [comment]
Ideia _oficial_ do protótipo da tela de autenticação de usuário criada, cores sujeitas a serem alteradas.

![image](https://user-images.githubusercontent.com/108769461/196311122-2f6a6f99-bf23-4a55-9853-bdc07c7ccf66.png)
